[package]
authors = ["Jeff Muizelaar <jmuizelaar@mozilla.com>"]
name = "pdb-downloader"
version = "0.1.0"

[dependencies]
goblin = "0.0.12"
indicatif = "0.8.0"
reqwest = "0.8.2"

[profile.release]
panic = "abort"
